sPath = '../../../../Results/PPI/735640.8990';
load([sPath, '/PPI1Linear']);
fprintf('Acquition ratio: %g\n', nnz(mask)/length(mask(:)));
errALPADMML = abs(xTrue-xALPADMML);
errALADMML = abs(xTrue-xALADMML);
errBOSVS = abs(xTrue-xBOSVS);
maxerr = max([errALPADMML(:); errALADMML(:); errBOSVS(:)]);
h = figure; imagesc(1:nRow,1:nCol,abs(xALPADMML)); colormap gray; axis image off; colorbar;
funCropEdge(h);
print(h, '-deps', [sPath, '/PPI1Linear_Recon_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALPADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Linear_Error_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xALADMML)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Linear_Recon_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Linear_Error_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xBOSVS)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Linear_Recon_BOSVS']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xBOSVS), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Linear_Error_BOSVS']);

load([sPath, '/PPI1Poisson']);
fprintf('Acquition ratio: %g\n', nnz(mask)/length(mask(:)));
errALPADMML = abs(xTrue-xALPADMML);
errALADMML = abs(xTrue-xALADMML);
errBOSVS = abs(xTrue-xBOSVS);
maxerr = max([errALPADMML(:); errALADMML(:); errBOSVS(:)]);
h = figure; imagesc(1:nRow,1:nCol,abs(xALPADMML)); colormap gray; axis image off; colorbar;
funCropEdge(h);
print(h, '-deps', [sPath, '/PPI1Poisson_Recon_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALPADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Poisson_Error_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xALADMML)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Poisson_Recon_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Poisson_Error_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xBOSVS)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Poisson_Recon_BOSVS']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xBOSVS), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI1Poisson_Error_BOSVS']);

load([sPath, '/PPI2Linear']);
fprintf('Acquition ratio: %g\n', nnz(mask)/length(mask(:)));
errALPADMML = abs(xTrue-xALPADMML);
errALADMML = abs(xTrue-xALADMML);
errBOSVS = abs(xTrue-xBOSVS);
maxerr = max([errALPADMML(:); errALADMML(:); errBOSVS(:)]);
h = figure; imagesc(1:nRow,1:nCol,abs(xALPADMML)); colormap gray; axis image off; colorbar;
funCropEdge(h);
print(h, '-deps', [sPath, '/PPI2Linear_Recon_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALPADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Linear_Error_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xALADMML)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Linear_Recon_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Linear_Error_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xBOSVS)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Linear_Recon_BOSVS']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xBOSVS), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Linear_Error_BOSVS']);

load([sPath, '/PPI2Poisson']);
fprintf('Acquition ratio: %g\n', nnz(mask)/length(mask(:)));
errALPADMML = abs(xTrue-xALPADMML);
errALADMML = abs(xTrue-xALADMML);
errBOSVS = abs(xTrue-xBOSVS);
maxerr = max([errALPADMML(:); errALADMML(:); errBOSVS(:)]);
h = figure; imagesc(1:nRow,1:nCol,abs(xALPADMML)); colormap gray; axis image off; colorbar;
funCropEdge(h);
print(h, '-deps', [sPath, '/PPI2Poisson_Recon_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALPADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Poisson_Error_ALPADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xALADMML)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Poisson_Recon_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xALADMML), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Poisson_Error_ALADMML']);
h = figure; imagesc(1:nRow,1:nCol,abs(xBOSVS)); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Poisson_Recon_BOSVS']);
h = figure; imagesc(1:nRow,1:nCol,abs(xTrue-xBOSVS), [0, maxerr]); colormap gray; axis image off; colorbar;
print(h, '-deps', [sPath, '/PPI2Poisson_Error_BOSVS']);

